### ISSUE TITLE
Autotile not working

### ISSUE THREAD

**Issue by rakun99** [MightyPrinny/godot-gputilemap#1]
Tried to use autotile, but that didn't worked.
Here's link to video of problem:
https://www.youtube.com/watch?v=kAVXpVuXRdo

**Comment by MightyPrinny** [comment]
Alright I was about to ask for details but I apparently  messed up the signal of an AcceptDialog when I was fixing the signals of some file dialogs, it should work now in the master branch.

**Comment by rakun99** [comment]
> Alright I was about to ask for details but I apparently messed up the signal of an AcceptDialog when I was fixing the signals of some file dialogs, it should work now in the master branch.


added video

**Comment by MightyPrinny** [comment]
> > Alright I was about to ask for details but I apparently messed up the signal of an AcceptDialog when I was fixing the signals of some file dialogs, it should work now in the master branch.
> 
> added video

I think you misunderstood my reply, I'm closing the issue because I fixed the issue, clone the master branch or check the releases tab and get version 0.9.8.

**Comment by rakun99** [comment]
Wow, it worked. Thanks. It all worked well. I also figured out how to make collisions, although didn't  understand that either:)
