### ISSUE TITLE
Cyclic Dependency Error

### ISSUE THREAD

**Issue by bitmapman5** [MightyPrinny/godot-gputilemap#4]
Hello, I'm very interested in trying out your addon for my project, however, there seems to be a cyclic dependency error in plugin.gd. I'm pretty sure this is a known GDScript bug but I thought I'd let you know in case you want to figure out a workaround. 
To reproduce this, just download and install the addon from the asset library in Godot 3.2.3 stable in any project and try to enable the plugin in project settings.
![gputilemap_cyclic_dependency](https://user-images.githubusercontent.com/58415811/97060892-e18ca000-1562-11eb-9014-1eb3c5ad3da7.png)

**Comment by DRON12261** [comment]
Same problem for Godot 3.2.3. I'd like to look at this addon.

**Comment by MightyPrinny** [comment]
I haven't used 3.2.3 yet, I'll look into it later
