### ISSUE TITLE
how to use the GPU tilemap?

### ISSUE THREAD

**Issue by Facundo15** [MightyPrinny/godot-gputilemap#5]
hi, i decided to try the plugin since godot's tilemap makes my game very slow, but there is no documentation of how to use it

**Comment by MightyPrinny** [comment]
There is some on the wiki page here and make sure download it from the master branch, I forgot to make a new release.

**Comment by Facundo15** [comment]
ok thanks, now i have a question the GPU tilemap can be used as a chunck? for example have several of these GPU tilemap and with a visibility notify instantiate the tilemap in the tree and then if necessary remove it Could this affect performance or would it be the same or worse? and could the map be updated at runtime?

**Comment by MightyPrinny** [comment]
Yes you can change them at runtime, the map is stored as pixels in a texture, there are some functions included for that or you could make your own if you learn how those work. I made this for a non procedural game, but you could implement some kind of chunk loading yourself, however, if it's not for some kind of procedural game and you have previously designed maps then you can just use multiple and the engine's culling should be enough to avoid wasting performance, the performance of drawing the map depends on how much of it is on screen, not on the size of the map.

**Comment by Facundo15** [comment]
/gpu_tilemap.gd:135 - Attempt to call function 'lock' in base 'null instance' on a null instance. -> when in the Map parameter I generate a new image_texture

/gpu_tilemap.gd:407 - Attempt to call function 'get_width' in base 'null instance' on a null instance. -> when he tried to paint he used the brush

**Comment by MightyPrinny** [comment]
Not sure what you did, but here's an example.
https://user-images.githubusercontent.com/18746022/122102910-f5339200-cde3-11eb-83c8-61b7f69a335c.mp4
